### ISSUE TITLE
DPU won't load my organization datasets

### ISSUE THREAD

**Issue by mvi-eea-sk** [OpenDataNode/UVPlugin-filesFromCKAN#8]
DPU won't load private datasets that belong to user organization.

This is caused by change in API call organization_show in CKAN from version 2.2.x to version 2.3 as it no longer returns resources, only datasets.

related: https://github.com/OpenDataNode/UVPlugin-relationalFromCKAN/issues/8

**Comment by eea03** [comment]
@mvi-eea-sk Is this issue tested? Can it be released?
I recently worked with this DPU and was accessing private dataset so for me it is OK
